### PR TITLE
Fix install of python package

### PR DESCRIPTION
**Pull request by ftalbrecht**
Depends on https://github.com/dune-community/dune-pybindxi/pull/7

### CODE REVIEW

**Comment by ftalbrecht** [comment]
This is the only of the `xt` modules which failes on these changes, and I cannon reproduce the issue locally. Any thoughts, @dune-community/dune-xt-devs?

**Comment by tobiasleibner** [comment]
The difference between this module and the other dune-xt modules was that dune-xt-data had a ``setup.py`` and the other modules each have a ``setup.py.in`` instead. For some reason, with the plain ``setup.py`` some files like ``dune-xt-data.egg-info`` are written in the source tree instead of the build directory. As the source tree is not writable on travis, the build fails. Locally, the source tree is writable, thus the error does not occur there.
I just renamed the ``setup.py`` to ``setup.py.in`` here, too. I am not sure what the difference in the handling of ``setup.py`` and ``setup.py.in`` actually is, so if we want a ``setup.py`` here we probably need to change the install script in ``dune-pybindxi``.

**Comment by renefritze** [comment]
In light of 
https://github.com/dune-community/dune-xt-data/pull/15/commits/da7ce0dda0c5f2ea3b2320fe0970fdf0913f7c17 fixing the build issue, maybe we should just enforce using a ```setup.py.in``` via the module install macro in Cmake?

**Comment by tobiasleibner** [comment]
I do not have an opinion on whether we also need to support ``setup.py``, opened https://github.com/dune-community/dune-pybindxi/issues/8 for discussion.

**Comment by ftalbrecht** [comment]
Ah, sorry for forgetting that. I used the same renaming in the other modules a few weeks back to make everything work. I should have recalled that :/
Thx for fixing

**Pull request merged**
